### ISSUE TITLE
Feat: Docker 파일 작성 및 배포에 필요한 gradl.yml 파일 작성, 로그아웃 기능 구현(보완 필요)

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#11]
### 💼 작업 설명
1. Docker 파일 작성 및 이미지 생성
2. 배포에 필요한 gradle.yml 파일 작성
3. 로그아웃 기능 구현
 
### ✅ To-do

- [x] Docker 파일 작성 및 이미지 생성
- [x] 배포에 필요한 gradle.yml 파일 작성
- [x] 로그아웃 기능 구현
