### ISSUE TITLE
Feat: Global 예외처리 로직 작성, 권한부여 로직 추가, 회원정보 수정 로직 및 필요없는 코드 삭제

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#15]
### 💼 작업 설명
- Global 예외처리 로직 작성
- 권한부여 로직 추가
- 회원정보 수정 로직 및 필요없는 코드 삭제
 
### ✅ To-do

- [x] Global 예외처리 로직 작성
- [x] 권한부여 로직 추가
- [x] 회원정보 수정 로직 및 필요없는 코드 삭제
