### ISSUE TITLE
Docs: Swagger.ui 문서화를 위한 로직, 의존성, 환경변수 작성 및 README.md 파일 생성

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#19]
### 💼 작업 설명
- Swagger 관련 파일 작성
- SpringDocs 의존성 추가
- 관련 환경변수 작성
- README.md 파일 생성
 
### ✅ To-do

- [x] Swagger 관련 파일 작성
- [x] SpringDocs 의존성 추가
- [x] 관련 환경변수 작성
- [x] README.md 파일 생성
