### ISSUE TITLE
Feat: 게시글 및 게시판 관련 엔티티 생성 및 User 엔티티와 연관관계 매핑 및 DTO, Repository, Service, Controller 파일 생성

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#21]
### 💼 작업 설명
- 게시글 및 게시판 관련 엔티티 생성
- User 엔티티와 연관관계 매핑
- 게시글 관련 DTO, Repository, Service, Controller 파일 생성

 
### ✅ To-do
- [x] 게시글 및 게시판 관련 엔티티 생성
- [x] User 엔티티와 연관관계 매핑
- [x] 게시글 관련 DTO, Repository, Service, Controller 파일 생성
