### ISSUE TITLE
Feat, Refactor: 게시판 생성 로직 작성, 사용하지 않는 import 삭제, DetailPostDetail 클래스의 toDto 메서드 static 추가

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#23]
### 💼 작업 설명
- 게시판 생성 로직 작성(board 테이블)
- 사용하지 않는 import 삭제
- DetailPostDetail 클래스의 toDto 메서드 static 추가
 
### ✅ To-do

- [x] 게시판 생성 로직 작성(board 테이블)
- [x] 사용하지 않는 import 삭제
- [x] DetailPostDetail 클래스의 toDto 메서드 static 추가
