### ISSUE TITLE
Feat: 회원 인증 정보 확인시 UserResponse의 아이디를 확인하는 getId() 메서드 추가, 회원 인증 정보 확인 메서드 추가, UserResponse id 필드 추가, UserController 스웨거 주석 수정 및 회원 탈퇴 메서드 ApiResponse 추가

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#25]
### 💼 작업 설명

- 회원 인증 정보 확인시 UserResponse의 아이디를 확인하는 getId() 메서드 추가
- 회원 인증 정보 확인 메서드 추가
- UserResponse id 필드 추가
- UserController 스웨거 주석 수정 및 회원 탈퇴 메서드 ApiResponse 추가

### ✅ To-do

- [x] 회원 인증 정보 확인시 UserResponse의 아이디를 확인하는 getId() 메서드 추가
- [x] 회원 인증 정보 확인 메서드 추가
- [x] UserResponse id 필드 추가
- [x] UserController 스웨거 주석 수정 및 회원 탈퇴 메서드 ApiResponse 추가
