### ISSUE TITLE
Refactor: UserService 자바독 추가 및 중복코드 정리, ../user/dto/request 폴더 admin과 user로 분리, UserController dto 클래스 이동 반영 및 apiResponse를 성공 여부에 따라 success, errorResponse로 수정

### ISSUE THREAD

**Issue by whwnsgh0258** [TableLink/TableLink-BE#34]
### 💼 작업 설명
- UserService 자바독 추가 및 중복코드 정리
- ../user/dto/request 폴더 admin과 user로 분리
- UserController dto 클래스 이동 반영 및 apiResponse를 성공 여부에 따라 success, errorResponse로 수정
 
### ✅ To-do

- [x] UserService 자바독 추가 및 중복코드 정리
- [x] ../user/dto/request 폴더 admin과 user로 분리
- [x] UserController dto 클래스 이동 반영 및 apiResponse를 성공 여부에 따라 success, errorResponse로 수정
